server {
    listen 8080;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
        add_header Pragma "no-cache";
        expires -1;
    }

    location /cal0app-latest.apk {
        root /usr/share/nginx/html;
        default_type application/vnd.android.package-archive;
        add_header Content-Disposition "attachment; filename=cal0app-latest.apk";
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
    }
}