server {
    listen 8080;
    server_name _;

    types {
        application/vnd.android.package-archive apk;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /cal0app-latest.apk {
        root /usr/share/nginx/html;
        add_header Content-Disposition "attachment; filename=cal0app-latest.apk";
    }
}