sonar.projectKey=faiz03-glicth_cal0appv2
sonar.organization=faiz03-glicth
sonar.projectName=cal0appv2
sonar.sources=lib
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,build/**
sonar.tests=test
sonar.sourceEncoding=UTF-8