import 'package:cal0appv2/models/report_model.dart';
import 'package:cal0appv2/services/users/report_service.dart';

class ReportRepository {
  final ReportService _service;

  ReportRepository({ReportService? service})
    : _service = service ?? ReportService();

  // ── User-side: submit a report ──────────────────────────────────────────

  /// Submits a new report on behalf of [userId].
  /// TODO(UC012/UC013 follow-up): confirm what a "report" represents for
  /// this app — a user-submitted issue/flag, or a generated usage/health
  /// summary — before building the submission UI on top of this method.
  Future<void> submitReport({
    required String userId,
    required String reportDetails,
  }) {
    final report = ReportModel(
      reportId: '', // generated by ReportService.addReport
      userId: userId,
      reportDetails: reportDetails,
      timestamp: DateTime.now(),
    );
    return _service.addReport(report);
  }

  // ── Admin-side: view user report (UC012) ────────────────────────────────

  /// Fetches all reports for the Admin "User Report" section.
  /// Returns an empty list when no reports exist — caller (ViewModel/View)
  /// is responsible for showing TC012_02's "No user reports available at
  /// this time." message in that case.
  Future<List<ReportModel>> getAllReports({int limit = 100}) =>
      _service.getAllReports(limit: limit);

  /// Reports submitted by a single user.
  Future<List<ReportModel>> getReportsForUser(String userId) =>
      _service.getReportsForUser(userId);

  Future<ReportModel?> getReport(String reportId) =>
      _service.getReport(reportId);

  // ── Admin-side: manage report ───────────────────────────────────────────

  Future<void> updateReport(ReportModel report) =>
      _service.updateReport(report);

  Future<void> deleteReport(String reportId) => _service.deleteReport(reportId);
}
